# Site settings
title: Meliodus.com
description: 'Freelance Paradise For Web Developers and Designers. <br> Email ~ support@meliodus.com <br>Call ~ (321) 121-3211'
url: 'http://meliodus.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Meliodus'
  email: support@meliodus.com
  twitter_username: meliodus
  #github_username:  meliodus
  #linkedin_username:  meliodus

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
